### ISSUE TITLE
travis: make-one-time-file.py:35: max([])

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#34]
https://travis-ci.org/mit-plv/fiat-crypto/jobs/146216010#L671

    Traceback (most recent call last):
      File "etc/coq-scripts/timing/make-one-time-file.py", line 35, in <module>
        table = make_table_string(times_dict)
      File "etc/coq-scripts/timing/make-one-time-file.py", line 17, in make_table_string
        times_width = max(max(map(len, times_dict.values())), len(sum_times(times_dict.values())))
    ValueError: max() arg is an empty sequence

An easy (and probably acceptable) fix would be to just not run this in the cases it fails.

**Comment by JasonGross** [comment]
Oh, right, I forgot that Coq 8.4 doesn't show times.
